server:
  port: 80

logging:
  level: info

spring:
  application:
    name: springboot
  datasource:
    url: jdbc:mysql:///springboot?useUnicode=true&amp;characterEncoding=utf-8&amp;serverTimezone=Asia/Shanghai&amp;autoReconnect=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  config-location:
  mapper-locations:
pagehelper:
  helper-dialect: mysql
  reasonable: !!str true
  support-methods-arguments: !!str true
  params: count=countSql

